Tools for track creation and editing.
Insprill/dv-mapify pull request #25
Opened 2023-08-12 23:01 UTC by WhistleWiz

This adds tools to create and edit tracks.
While most of the work can be done through a new editor window, all the functions are accessible without it.

2023-08-13 00:14 UTC, Insprill requested changes
Thank you for the PR! Mostly just code-style things.

As a side note, are you willing to maintain this should any issues arise, or should any new features be added?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                    //pivot + dir * (turntableOptions.TurntableRadius + turntableOptions.ExitTrackLength) };
Can these be removed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                return new Vector3[][]
Most arrays don't need an explicit type defined (this goes for many others here, and in other files)
```suggestion
                return new[]

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                Vector3 offset = Vector3.zero;
Can this be assigned in the if-statement where it's used?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                Vector3[][] temp;
```suggestion

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                temp = PreviewSwitchSprawl(leftPrefab, rightPrefab, yardOptions, currentOrientation, trackDistance,
```suggestion
                Vector3[][] temp = PreviewSwitchSprawl(leftPrefab, rightPrefab, yardOptions, currentOrientation, trackDistance,

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                Vector3 mid1;
```suggestion

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                mid0 = temp[0][1];
```suggestion
                Vector3 mid0 = temp[0][1];
                Vector3 mid1;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                Vector3[] points4 = new Vector3[0];
All empty arrays should be created with `Array.Empty<Type>()` since it avoids an allocation. (this goes for many others here, and in other files)

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                float dist;
```suggestion

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                dist = mid1.z - mid0.z;
```suggestion
                float dist = mid1.z - mid0.z;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                // TODO: fix lengths.
Has this been done?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +            internal static Vector3[] StraightNormal(Vector3 start, Vector3 dir, float length)
Does this need to be internal or can it be made private?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                if (reverse)
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +            internal static YardCache? CachedYard = null;
```suggestion
            internal static YardCache? CachedYard;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +            // Not too elegant, but it's the easiest way to calculate the lenghts of everything without having
```suggestion
            // Not too elegant, but it's the easiest way to calculate the lengths of everything without having

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.cs
> +            yardObj.transform.rotation = Quaternion.LookRotation(attachPoint - handlePosition);
You can use an object initialize for this
```suggestion
            GameObject yardObj = new GameObject($"Yard [Station:{stationId}]/[ID:{yardId}]")
            {
                transform =
                {
                    parent = parent,
                    position = attachPoint,
                    rotation = Quaternion.LookRotation(attachPoint - handlePosition)
                }
            };

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.cs
> +                }
This can be a ternary
```suggestion
                t = (side1[i].position - side3[i].position).sqrMagnitude > 0
                    ? CreateStraight2Point(trackPrefab, yardObj.transform, side1[i].position, side3[i].position, false)
                    : null;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.cs
> +                }
Same here
```suggestion
                t = (side2[i].position - side4[i].position).sqrMagnitude > 0 ?
                    CreateStraight2Point(trackPrefab, yardObj.transform, side2[i].position, side4[i].position, false)
                    : null;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsHelper.cs
> +            //return 60.0f * Mathf.Sqrt(radius / 230.0f);
Is this still needed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsHelper.cs
> +            // Based on certain ingame findings.
Can you provide references here should the values change?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsHelper.cs
> +        }
This doesn't appear to be used, can it be deleted?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/EditorHelper.cs
> +        }
None of these appear to be used.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/EditorHelper.cs
> +            else
This else is redundant.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/EditorHelper.cs
> +            if (show)
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/Extensions.cs
> +        }
These don't appear to be used.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +        }
Unused.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +            float f;
```suggestion

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +                f = i / (float)(samples - 1);
```suggestion
                float f = i / (float)(samples - 1);

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +            float cos;
```suggestion

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +                cos = Mathf.Cos(angle);
```suggestion
                float angle = (Tau * i) / samples;
                float sin = Mathf.Sin(angle);
                float cos = Mathf.Cos(angle);

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Utils/MathHelper.cs
> +            else
This else is redundant.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        {
Arrays created like this don't need an explicit type
```suggestion
        private readonly GUIContent[] _modeContents = {

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        public Switch CurrentSwitch => _isLeft ? LeftSwitch : RightSwitch;
Unused.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                    case SelectionType.None:
This case is redundant.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            //EditorGUILayout.LabelField("", (GUIStyle)"Tooltip", GUILayout.MaxHeight(1));
Is this needed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                if (GUILayout.Button(new GUIContent("Swap tracks", "Swaps the selected track between the through and diverging tracks")))
This if statement could be merged with the enclosing one to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                new GUIContent($"Current point"),
```suggestion
                new GUIContent("Current point"),

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab"))
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab"))
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(LeftSwitch, "Left switch prefab") &&
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab") &&
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                        //}
Is this needed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                if (_showYardCache)
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TurntablePrefab, "Turntable prefab"))
This should be inverted to reduce nesting.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(LeftSwitch, "Left switch prefab") &&
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab"))
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab") &&
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab") &&
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (Require(TrackPrefab, "Track prefab") &&
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            string tooltip = "";
```suggestion
            string tooltip;

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                null, null);
Null is the default style and menuAction, no need to specify them explicitly.
```suggestion
            _showEditing = EditorGUILayout.BeginFoldoutHeaderGroup(_showEditing,
                new GUIContent("Editing", "Ways to edit tracks after they've been created"));

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            var menu = new GenericMenu();
Please use explicit types instead of var.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            var menu = new GenericMenu();
Here too.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                    break;
This is redundant.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        private void CreateConnect2(Vector3 attachPoint, Vector3 handlePosition)
Neither parameter here is used. Is that a bug or can they be removed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            if (CurrentTrack)
Invert.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            {
Is this needed?

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        private void DrawHandles(SceneView scene)
This should be broken up into multiple methods.

2023-08-13 00:14 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            else
This else is redundant.

2023-08-13 00:32 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +            internal static YardCache? CachedYard = null;
Should the null not be assigned to explicitly state my intention?

2023-08-13 00:43 UTC, Insprill commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +            internal static YardCache? CachedYard = null;
Since it's a nullable type, it's implied that it's null unless explicitly set to something.

2023-08-17 23:58 UTC, WhistleWiz reviewed
Applied most of the changes, fixed bugs and added a feature regarding checks.
Didn't realise I had to press a button to get the review through...

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                return new Vector3[][]
I had to do it this way since I worked on this directly as a unity project, unity always complaining if there was not the full declaration.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Utils/Extensions.cs
> +        }
They are slightly faster than checking the grade normally, so I may keep them.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Utils/EditorHelper.cs
> +        }
Separator was a relic of times past, 2 of the sliders were made to match the 3 versions unity shows by default. The GUIContent version was actually created as part of an editing tool that has not yet been ported from when I made these as components instead of proper editors, so it'll stay for when that gets added.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsHelper.cs
> +            //return 60.0f * Mathf.Sqrt(radius / 230.0f);
Very likely not but leaving it as a precaution.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsHelper.cs
> +        }
It was supposed to be used on the track merging part, but I'm keeping it for the track splitting later.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                Vector3 offset = Vector3.zero;
Yeah, before this was finished properly it had to be initialized or VS would complain.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsCreator.Previews.cs
> +                // TODO: fix lengths.
Nope, still haven't figured out the bug but this is used for display purposes only, so it is not seen nor does it affect anything else.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        {
More of unity's relics not allowing me to do so.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                        //}
Leaving it for when the length calculations are fixed.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +        private void CreateConnect2(Vector3 attachPoint, Vector3 handlePosition)
Yup, more artifacts of the previous implementation.

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +            {
Cut feature for this release...

2023-08-17 23:58 UTC, WhistleWiz commented on MapifyEditor/Tools/TrackToolsWindow.cs
> +                if (GUILayout.Button(new GUIContent("Swap tracks", "Swaps the selected track between the through and diverging tracks")))
Leaving as is for now to guarantee the short circuit and not draw the button.

2023-08-31 17:54 UTC, t0stiman commented
Thanks for your work on this project @WhistleWiz ! 

One issue I found when generating a turntable:

![20230831195231_1](https://github.com/Insprill/dv-mapify/assets/18124323/ed54d9db-36c3-423b-8f63-120e615df455)

2023-09-04 18:46 UTC, t0stiman commented
The turntable bug I mentioned turned out to be my fault, ignore that.

2023-09-06 14:49 UTC, t0stiman commented
I've been testing the track tools and it all seems to work well 👍

@Insprill any chance of a PR approval soon? :)

2023-11-07 03:47 UTC, Insprill approved these changes
LGTM. Thank you! 🥳

2023-11-07 03:47 UTC, merged