Fix water tower 2 and dumpster rotation
Insprill/dv-mapify pull request #33
Opened 2023-10-13 13:47 UTC by t0stiman

Fixes #27

2023-10-13 14:40 UTC, t0stiman commented
I broke something, setting this to draft for now

2023-10-13 14:51 UTC, t0stiman commented
I forgot to update the MapifyEditor.dll in my Unity project.
![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/290073b8-3f9c-4199-935a-c87d9e243438)

2023-11-07 02:55 UTC, Insprill requested changes
Instead of rotating the objects once they get spawned in, I believe the problem is that my models don't match the rotation of the DV models. This would be fairly easy to check by using AssetRipper to export the DV model, then putting both into Blender as-is and seeing if they line up.

2023-11-07 02:55 UTC, Insprill commented on MapifyEditor/Vanilla/VanillaObject.cs
> +        public Vector3 rotation = Vector3.zero;
This should be renamed "rotationOffset" or something similar since it's not setting the exact rotation.

2023-11-07 22:50 UTC, Insprill commented
Interesting. The model must be rotated under the root in the base game then.

2023-11-07 22:51 UTC, Insprill requested changes

2023-11-07 22:51 UTC, Insprill commented on MapifyEditor/Vanilla/VanillaObject.cs
> +        [FormerlySerializedAs("rotation")] public Vector3 rotationOffset = Vector3.zero;
Please remove the FormerlySerializedAs attribute and ensure all prefabs are saved with the new name and the correct data.

2023-11-09 05:38 UTC, Insprill approved these changes
LGTM. Thank you!

2023-11-09 05:38 UTC, merged